import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MenuNavDesktop, MenuNavMobile } from "./components";
import Transition from "./transition";


const bebasNeue = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: '--font-bebas-neue',
  weight: "400",
  display: 'swap',
});

const robotoMono = localFont({
  src: "./fonts/RobotoMono-VariableFont_wght.ttf",
  variable: '--font-roboto-mono',
  weight: "400",
  display: 'swap',
});

const inter = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: '--font-inter',
  weight: "400",
  display: 'swap',
});
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable} ${bebasNeue.variable}`}>
      <body className={`antialiased  bg-hero-pattern bg-no-repeat bg-center min-h-svh`}>
        <Transition>{children}</Transition>
        <div className="hidden sm:block">
          <MenuNavDesktop />
        </div>
        <div className="block sm:hidden">
          <MenuNavMobile />
        </div>
      </body>
    </html>
  );
}
